import type { DemoEvent, EventCategory } from "./types";

export const CATEGORY_LABELS: Record<EventCategory, string> = {
  "supper-clubs": "supper clubs",
  workshops: "workshops",
  nightlife: "nightlife",
  "live-music": "live music",
  markets: "markets & pop-ups",
  "pickup-sports": "pickup sports",
  wellness: "wellness",
  "talks-film": "talks & film",
};

export const CATEGORY_PALETTES: Record<EventCategory, [string, string]> = {
  "supper-clubs": ["#3A2E1E", "#C2A968"],
  workshops: ["#382B23", "#BC8E71"],
  nightlife: ["#292433", "#8E7CA8"],
  "live-music": ["#3A2A28", "#B5736E"],
  markets: ["#28352B", "#7A9E6E"],
  "pickup-sports": ["#26303C", "#8FA9C9"],
  wellness: ["#243330", "#6E9CA0"],
  "talks-film": ["#2B2A36", "#A8A2C9"],
};

/**
 * The seed catalogue — a simulated week of lagos events. `dayOffset` is days
 * from "today" at runtime (negative = past), so the world never goes stale.
 * Prices are illustrative naira.
 */
export const SEED_EVENTS: DemoEvent[] = [
  // ── the featured shared event — every role's home surfaces this one ──
  {
    id: "vinyl-and-supper",
    image: "/demo/vinyl-and-supper.jpg",
    title: "jollof & vinyl",
    category: "supper-clubs",
    area: "lekki",
    venueName: "the greenhouse",
    hostName: "tolu's table",
    hostId: "maya",
    talentNames: ["emeka okafor"],
    dayOffset: 2,
    startTime: "19:30",
    price: 12000,
    capacity: 48,
    going: 34,
    blurb:
      "a supper club that turns into a listening party. three courses of home cooking, then emeka opens the record boxes until late.",
    tags: ["long tables", "vinyl only", "byob"],
    palette: ["#3A2E1E", "#D4B461"],
    featured: true,
  },

  // ── tonight ──
  {
    id: "rooftop-listening",
    image: "/demo/rooftop-listening.jpg",
    title: "rooftop sundown session",
    category: "nightlife",
    area: "victoria island",
    venueName: "the rooftop, vi",
    hostName: "slow wave",
    dayOffset: 0,
    startTime: "18:00",
    price: 0,
    capacity: 80,
    going: 71,
    blurb: "amapiano and alté on the rooftop as the sun drops over the lagoon. come early.",
    tags: ["free entry", "sunset", "outdoors"],
    palette: ["#292433", "#9C8BBB"],
  },
  {
    id: "run-club-social",
    image: "/demo/run-club-social.jpg",
    title: "5k + suya run club",
    category: "pickup-sports",
    area: "lekki",
    venueName: "lekki conservation gate",
    hostName: "lagos road runners",
    dayOffset: 0,
    startTime: "18:30",
    price: 0,
    capacity: 60,
    going: 44,
    blurb: "an easy 5k loop, all paces, then suya and drinks. first-timers get their skewer sorted.",
    tags: ["all paces", "social", "weekly"],
    palette: ["#26303C", "#8FA9C9"],
  },
  {
    id: "life-drawing-late",
    image: "/demo/life-drawing-late.jpg",
    title: "life drawing, but loud",
    category: "workshops",
    area: "yaba",
    venueName: "the shop, yaba",
    hostName: "drawn together",
    dayOffset: 0,
    startTime: "19:00",
    price: 4000,
    capacity: 35,
    going: 33,
    blurb: "untutored life drawing with a live dj. materials provided, judgement not.",
    tags: ["materials included", "beginners welcome"],
    palette: ["#38301F", "#C2A968"],
  },
  {
    id: "kitchen-takeover-thai",
    image: "/demo/kitchen-takeover-thai.jpg",
    title: "aunty nkechi's kitchen takeover",
    category: "supper-clubs",
    area: "surulere",
    venueName: "the yard, surulere",
    hostName: "aunty nkechi",
    dayOffset: 0,
    startTime: "19:00",
    price: 8000,
    capacity: 30,
    going: 27,
    blurb: "eastern nigerian home cooking, one night only. ofe onugbu and more, family style.",
    tags: ["family style", "spicy", "one night"],
    palette: ["#3A2E1E", "#C2A968"],
  },
  {
    id: "open-decks",
    image: "/demo/open-decks.jpg",
    title: "open decks night",
    category: "nightlife",
    area: "yaba",
    venueName: "the warehouse, yaba",
    hostName: "first spin",
    dayOffset: 0,
    startTime: "20:00",
    price: 2000,
    capacity: 120,
    going: 58,
    blurb: "thirty-minute slots, proper rig, friendly room. sign up on the door.",
    tags: ["open slots", "late night"],
    palette: ["#292433", "#8E7CA8"],
  },

  // ── tomorrow ──
  {
    id: "ceramics-beginners",
    image: "/demo/ceramics-beginners.jpg",
    title: "wheel throwing for beginners",
    category: "workshops",
    area: "yaba",
    venueName: "nkechi's studio",
    hostName: "nkechi throws",
    dayOffset: 1,
    startTime: "18:30",
    price: 15000,
    capacity: 12,
    going: 12,
    blurb: "two hours on the wheel, aprons on, mess guaranteed. pieces fired and kept for you.",
    tags: ["sold out often", "hands on", "take home"],
    palette: ["#382B23", "#BC8E71"],
  },
  {
    id: "jazz-in-the-crypt",
    image: "/demo/jazz-in-the-crypt.jpg",
    title: "jazz at freedom park",
    category: "live-music",
    area: "lagos island",
    venueName: "freedom park",
    hostName: "afropolitan sessions",
    dayOffset: 1,
    startTime: "20:00",
    price: 6000,
    capacity: 70,
    going: 52,
    blurb: "the highlife trio play two open-air sets under the trees. bring a friend.",
    tags: ["open air", "two sets"],
    palette: ["#3A2A28", "#B5736E"],
  },
  {
    id: "padel-mixer",
    image: "/demo/padel-mixer.jpg",
    title: "padel mixer — all levels",
    category: "pickup-sports",
    area: "ikoyi",
    venueName: "ikoyi club courts",
    hostName: "padel lagos",
    dayOffset: 1,
    startTime: "19:00",
    price: 5000,
    capacity: 24,
    going: 19,
    blurb: "rotating doubles so you play with everyone. rackets to borrow, balls provided.",
    tags: ["all levels", "equipment provided"],
    palette: ["#26303C", "#8FA9C9"],
  },
  {
    id: "natural-wine-101",
    image: "/demo/natural-wine-101.jpg",
    title: "wine & small chops, zero snobbery",
    category: "talks-film",
    area: "lekki",
    venueName: "the greenhouse",
    hostName: "tap & tapper",
    dayOffset: 1,
    startTime: "19:30",
    price: 7000,
    capacity: 40,
    going: 31,
    blurb: "six pours, no jargon, small chops on the side. learn what you actually like and why.",
    tags: ["six pours", "beginners welcome"],
    palette: ["#2B2A36", "#A8A2C9"],
  },

  // ── this week ──
  {
    id: "amapiano-night",
    image: "/demo/amapiano-night.jpg",
    title: "piano night: amapiano special",
    category: "nightlife",
    area: "lekki",
    venueName: "the loft, lekki",
    hostName: "log drum lagos",
    dayOffset: 3,
    startTime: "22:00",
    price: 8000,
    capacity: 150,
    going: 122,
    blurb: "log drums until 4am. emeka okafor on the opening set.",
    talentNames: ["emeka okafor"],
    tags: ["late", "amapiano"],
    palette: ["#292433", "#8E7CA8"],
  },
  {
    id: "film-club-outdoor",
    image: "/demo/film-club-outdoor.jpg",
    title: "rooftop film club: lionheart",
    category: "talks-film",
    area: "yaba",
    venueName: "alliance rooftop",
    hostName: "reel lagos",
    dayOffset: 3,
    startTime: "21:00",
    price: 5000,
    capacity: 90,
    going: 74,
    blurb: "genevieve nnaji under the sky, headphones on, seats out.",
    tags: ["headphones", "seats provided"],
    palette: ["#2B2A36", "#A8A2C9"],
  },
  {
    id: "pasta-masterclass",
    image: "/demo/pasta-masterclass.jpg",
    title: "fresh pasta masterclass",
    category: "workshops",
    area: "lekki",
    venueName: "flour + fire",
    hostName: "nonna lagos",
    dayOffset: 4,
    startTime: "18:00",
    price: 18000,
    capacity: 16,
    going: 11,
    blurb: "hand-rolled tagliatelle from scratch, then you eat your homework.",
    tags: ["dinner included", "hands on"],
    palette: ["#3A2E1E", "#C2A968"],
  },
  {
    id: "vinyl-market",
    image: "/demo/vinyl-market.jpg",
    title: "crate diggers record fair",
    category: "markets",
    area: "surulere",
    venueName: "the yard, surulere",
    hostName: "crate diggers",
    dayOffset: 4,
    startTime: "11:00",
    price: 0,
    capacity: 300,
    going: 96,
    blurb: "forty sellers, one yard, coffee and small chops. early entry for members.",
    tags: ["free entry", "early access drop"],
    palette: ["#28352B", "#7A9E6E"],
  },

  // ── the weekend ──
  {
    id: "sunday-league-fives",
    image: "/demo/sunday-league-fives.jpg",
    title: "sunday five-a-side pickup",
    category: "pickup-sports",
    area: "lekki",
    venueName: "astro turf, lekki",
    hostName: "casual fc",
    dayOffset: 5,
    startTime: "10:00",
    price: 2500,
    capacity: 30,
    going: 24,
    blurb: "mixed-ability fives, bibs and balls sorted. winners stay on.",
    tags: ["mixed ability", "weekly"],
    palette: ["#26303C", "#8FA9C9"],
  },
  {
    id: "flea-and-food",
    image: "/demo/flea-and-food.jpg",
    title: "lekki flea & food yard",
    category: "markets",
    area: "lekki",
    venueName: "the yard, lekki",
    hostName: "made in lagos",
    dayOffset: 5,
    startTime: "10:00",
    price: 0,
    capacity: 500,
    going: 210,
    blurb: "thrift, vintage, records and food stalls. bring cash and an appetite.",
    tags: ["free entry", "outdoors"],
    palette: ["#28352B", "#7A9E6E"],
  },
  {
    id: "sound-bath",
    image: "/demo/sound-bath.jpg",
    title: "saturday sound bath",
    category: "wellness",
    area: "ikoyi",
    venueName: "the still room",
    hostName: "still point",
    dayOffset: 5,
    startTime: "09:30",
    price: 7000,
    capacity: 25,
    going: 21,
    blurb: "an hour under gongs and singing bowls. mats provided, phones off.",
    tags: ["mats provided", "morning"],
    palette: ["#243330", "#6E9CA0"],
  },
  {
    id: "block-party",
    image: "/demo/block-party.jpg",
    title: "freedom way block party",
    category: "nightlife",
    area: "lekki",
    venueName: "freedom way",
    hostName: "streets ahead",
    dayOffset: 6,
    startTime: "14:00",
    price: 3000,
    capacity: 400,
    going: 287,
    blurb: "three sound systems, food from the yard, day into night.",
    tags: ["outdoors", "family friendly until 7"],
    palette: ["#292433", "#8E7CA8"],
  },
  {
    id: "long-table-lunch",
    image: "/demo/long-table-lunch.jpg",
    title: "long table sunday lunch",
    category: "supper-clubs",
    area: "ikoyi",
    venueName: "the terminal, vi",
    hostName: "gather round",
    dayOffset: 6,
    startTime: "13:00",
    price: 12000,
    capacity: 60,
    going: 38,
    blurb: "one long table, four courses, strangers on purpose. seconds encouraged.",
    tags: ["four courses", "communal"],
    palette: ["#3A2E1E", "#C2A968"],
  },
  {
    id: "morning-rave",
    image: "/demo/morning-rave.jpg",
    title: "sober morning rave",
    category: "wellness",
    area: "lekki",
    venueName: "the deck, lekki",
    hostName: "daybreaker lagos",
    dayOffset: 6,
    startTime: "07:00",
    price: 6000,
    capacity: 200,
    going: 134,
    blurb: "two hours of proper dancing before work exists. smoothies, not spirits.",
    tags: ["alcohol free", "morning"],
    palette: ["#243330", "#6E9CA0"],
  },

  // ── next week ──
  {
    id: "supper-club-vol-9",
    image: "/demo/supper-club-vol-9.jpg",
    title: "tolu's table — vol. 9",
    category: "supper-clubs",
    area: "lekki",
    venueName: "the greenhouse",
    hostName: "tolu's table",
    hostId: "maya",
    dayOffset: 9,
    startTime: "19:30",
    price: 15000,
    capacity: 12,
    going: 7,
    blurb: "the flagship: twelve seats, five courses, one playlist built live by the table.",
    tags: ["twelve seats", "five courses"],
    palette: ["#3A2E1E", "#D4B461"],
  },
  {
    id: "poetry-open-mic",
    image: "/demo/poetry-open-mic.jpg",
    title: "unmuted: poetry open mic",
    category: "talks-film",
    area: "victoria island",
    venueName: "terra kulture",
    hostName: "unmuted",
    dayOffset: 8,
    startTime: "19:30",
    price: 2000,
    capacity: 60,
    going: 26,
    blurb: "eight open slots, two features, one very kind room.",
    tags: ["open slots", "first timers cheered"],
    palette: ["#2B2A36", "#A8A2C9"],
  },
  {
    id: "banya-social",
    image: "/demo/banya-social.jpg",
    title: "steam & cold plunge social",
    category: "wellness",
    area: "victoria island",
    venueName: "the spa, vi",
    hostName: "hot cold club",
    dayOffset: 8,
    startTime: "18:00",
    price: 9000,
    capacity: 20,
    going: 14,
    blurb: "steam, plunge, repeat — then tea and big talk on the deck.",
    tags: ["towels provided", "small group"],
    palette: ["#243330", "#6E9CA0"],
  },
  {
    id: "screen-print-crash",
    image: "/demo/screen-print-crash.jpg",
    title: "screen printing crash course",
    category: "workshops",
    area: "yaba",
    venueName: "print house, yaba",
    hostName: "pull & press",
    dayOffset: 10,
    startTime: "18:30",
    price: 12000,
    capacity: 14,
    going: 6,
    blurb: "design, expose and pull your own two-colour print in one evening.",
    tags: ["take home", "materials included"],
    palette: ["#382B23", "#BC8E71"],
  },
  {
    id: "garage-revival",
    image: "/demo/garage-revival.jpg",
    title: "alté night: all vinyl",
    category: "nightlife",
    area: "surulere",
    venueName: "the warehouse, surulere",
    hostName: "steppers",
    dayOffset: 11,
    startTime: "21:00",
    price: 4000,
    capacity: 180,
    going: 61,
    blurb: "afrobeats and alté on wax until 2. dress code: comfortable shoes.",
    tags: ["vinyl only", "alté"],
    palette: ["#292433", "#8E7CA8"],
  },
  {
    id: "makers-market",
    image: "/demo/makers-market.jpg",
    title: "small makers sunday market",
    category: "markets",
    area: "ikoyi",
    venueName: "the courtyard, ikoyi",
    hostName: "made nearby",
    dayOffset: 12,
    startTime: "10:00",
    price: 0,
    capacity: 250,
    going: 44,
    blurb: "thirty local makers — ceramics, prints, small-batch everything.",
    tags: ["free entry", "local makers"],
    palette: ["#28352B", "#7A9E6E"],
  },
  {
    id: "climbing-social",
    image: "/demo/climbing-social.jpg",
    title: "beginners bouldering social",
    category: "pickup-sports",
    area: "lekki",
    venueName: "the wall, lekki",
    hostName: "grip & grin",
    dayOffset: 12,
    startTime: "19:00",
    price: 6000,
    capacity: 40,
    going: 18,
    blurb: "intro session, shoe hire included, pizza after. no upper-body strength required.",
    tags: ["beginners", "pizza after"],
    palette: ["#26303C", "#8FA9C9"],
  },

  // ── recently past — powers amaka's history, tolu's track record, reviews ──
  {
    id: "table-vol-8",
    image: "/demo/table-vol-8.jpg",
    title: "tolu's table — vol. 8",
    category: "supper-clubs",
    area: "yaba",
    venueName: "the shop, yaba",
    hostName: "tolu's table",
    hostId: "maya",
    dayOffset: -6,
    startTime: "19:30",
    price: 12000,
    capacity: 12,
    going: 12,
    blurb: "twelve strangers, five courses, one very long argument about the best suya spot.",
    tags: ["sold out"],
    palette: ["#3A2E1E", "#D4B461"],
  },
  {
    id: "table-vol-7",
    image: "/demo/table-vol-7.jpg",
    title: "tolu's table — vol. 7",
    category: "supper-clubs",
    area: "lekki",
    venueName: "the greenhouse",
    hostName: "tolu's table",
    hostId: "maya",
    dayOffset: -21,
    startTime: "19:30",
    price: 12000,
    capacity: 12,
    going: 12,
    blurb: "the one with the plantain course everyone still talks about.",
    tags: ["sold out"],
    palette: ["#3A2E1E", "#D4B461"],
  },
  {
    id: "ceramics-past",
    image: "/demo/ceramics-past.jpg",
    title: "yaba ceramics evening",
    category: "workshops",
    area: "yaba",
    venueName: "nkechi's studio",
    hostName: "nkechi throws",
    dayOffset: -4,
    startTime: "18:30",
    price: 15000,
    capacity: 12,
    going: 12,
    blurb: "hand-building session — pinch pots and small victories.",
    tags: ["hands on"],
    palette: ["#382B23", "#BC8E71"],
  },
  {
    id: "dub-past",
    image: "/demo/dub-past.jpg",
    title: "dub in the yard",
    category: "nightlife",
    area: "surulere",
    venueName: "the warehouse, surulere",
    hostName: "heavyweight sound",
    dayOffset: -9,
    startTime: "20:00",
    price: 4000,
    capacity: 120,
    going: 118,
    blurb: "one stack, one selector, no requests.",
    tags: ["sound system"],
    palette: ["#292433", "#8E7CA8"],
  },
];

export function eventById(id: string) {
  return SEED_EVENTS.find((e) => e.id === id);
}
