import type { DemoEvent, EventCategory } from "./types";

export const CATEGORY_LABELS: Record<EventCategory, string> = {
  "supper-clubs": "supper clubs",
  workshops: "workshops",
  nightlife: "nightlife",
  "live-music": "live music",
  markets: "markets & pop-ups",
  "pickup-sports": "pickup sports",
  wellness: "wellness",
  "talks-film": "talks & film",
};

export const CATEGORY_PALETTES: Record<EventCategory, [string, string]> = {
  "supper-clubs": ["#3A2E1E", "#C2A968"],
  workshops: ["#382B23", "#BC8E71"],
  nightlife: ["#292433", "#8E7CA8"],
  "live-music": ["#3A2A28", "#B5736E"],
  markets: ["#28352B", "#7A9E6E"],
  "pickup-sports": ["#26303C", "#8FA9C9"],
  wellness: ["#243330", "#6E9CA0"],
  "talks-film": ["#2B2A36", "#A8A2C9"],
};

/**
 * The seed catalogue. `dayOffset` is days from "today" at runtime
 * (negative = past), so the world never goes stale.
 */
export const SEED_EVENTS: DemoEvent[] = [
  // ── the featured shared event — every role's home surfaces this one ──
  {
    id: "vinyl-and-supper",
    image: "/demo/vinyl-and-supper.jpg",
    title: "vinyl & supper",
    category: "supper-clubs",
    area: "peckham",
    venueName: "the glasshouse",
    hostName: "table for twelve",
    hostId: "maya",
    talentNames: ["jerome okafor"],
    dayOffset: 2,
    startTime: "19:30",
    price: 28,
    capacity: 48,
    going: 34,
    blurb:
      "a supper club that turns into a listening party. three west african sharing courses, then jerome opens the record boxes until late.",
    tags: ["long tables", "vinyl only", "byob"],
    palette: ["#3A2E1E", "#D4B461"],
    featured: true,
  },

  // ── tonight ──
  {
    id: "rooftop-listening",
    image: "/demo/rooftop-listening.jpg",
    title: "rooftop listening session",
    category: "nightlife",
    area: "peckham",
    venueName: "rye studios rooftop",
    hostName: "slow wave",
    dayOffset: 0,
    startTime: "18:00",
    price: 0,
    capacity: 80,
    going: 71,
    blurb: "ambient and dub on the rooftop while the sun goes down. bring a layer.",
    tags: ["free entry", "sunset", "outdoors"],
    palette: ["#292433", "#9C8BBB"],
  },
  {
    id: "run-club-social",
    image: "/demo/run-club-social.jpg",
    title: "5k + pints run club",
    category: "pickup-sports",
    area: "victoria park",
    venueName: "park gates east",
    hostName: "east side runners",
    dayOffset: 0,
    startTime: "18:30",
    price: 0,
    capacity: 60,
    going: 44,
    blurb: "an easy 5k loop, all paces, then the pub. first-timers get their pint bought.",
    tags: ["all paces", "social", "weekly"],
    palette: ["#26303C", "#8FA9C9"],
  },
  {
    id: "life-drawing-late",
    image: "/demo/life-drawing-late.jpg",
    title: "life drawing, but loud",
    category: "workshops",
    area: "hackney",
    venueName: "the corner store",
    hostName: "drawn together",
    dayOffset: 0,
    startTime: "19:00",
    price: 12,
    capacity: 35,
    going: 33,
    blurb: "untutored life drawing with a live dj. materials provided, judgement not.",
    tags: ["materials included", "beginners welcome"],
    palette: ["#38301F", "#C2A968"],
  },
  {
    id: "kitchen-takeover-thai",
    image: "/demo/kitchen-takeover-thai.jpg",
    title: "aunty noi's kitchen takeover",
    category: "supper-clubs",
    area: "dalston",
    venueName: "mangal yard",
    hostName: "aunty noi",
    dayOffset: 0,
    startTime: "19:00",
    price: 22,
    capacity: 30,
    going: 27,
    blurb: "northern thai home cooking, one night only. som tam made to order, family style.",
    tags: ["family style", "spicy", "one night"],
    palette: ["#3A2E1E", "#C2A968"],
  },
  {
    id: "open-decks",
    image: "/demo/open-decks.jpg",
    title: "open decks night",
    category: "nightlife",
    area: "deptford",
    venueName: "arch 42",
    hostName: "first spin",
    dayOffset: 0,
    startTime: "20:00",
    price: 5,
    capacity: 120,
    going: 58,
    blurb: "thirty-minute slots, proper rig, friendly room. sign up on the door.",
    tags: ["open slots", "late licence"],
    palette: ["#292433", "#8E7CA8"],
  },

  // ── tomorrow ──
  {
    id: "ceramics-beginners",
    image: "/demo/ceramics-beginners.jpg",
    title: "wheel throwing for beginners",
    category: "workshops",
    area: "hackney",
    venueName: "mona's studio",
    hostName: "mona throws",
    dayOffset: 1,
    startTime: "18:30",
    price: 35,
    capacity: 12,
    going: 12,
    blurb: "two hours on the wheel, aprons on, mess guaranteed. pieces fired and posted.",
    tags: ["sold out often", "hands on", "take home"],
    palette: ["#382B23", "#BC8E71"],
  },
  {
    id: "jazz-in-the-crypt",
    image: "/demo/jazz-in-the-crypt.jpg",
    title: "jazz in the crypt",
    category: "live-music",
    area: "camberwell",
    venueName: "st giles crypt",
    hostName: "low ceiling sessions",
    dayOffset: 1,
    startTime: "20:00",
    price: 15,
    capacity: 70,
    going: 52,
    blurb: "strings attached trio play two candlelit sets under the church. byo cushions.",
    tags: ["candlelit", "two sets"],
    palette: ["#3A2A28", "#B5736E"],
  },
  {
    id: "padel-mixer",
    image: "/demo/padel-mixer.jpg",
    title: "padel mixer — all levels",
    category: "pickup-sports",
    area: "canada water",
    venueName: "dockside courts",
    hostName: "padel people",
    dayOffset: 1,
    startTime: "19:00",
    price: 10,
    capacity: 24,
    going: 19,
    blurb: "rotating doubles so you play with everyone. rackets to borrow, balls provided.",
    tags: ["all levels", "equipment provided"],
    palette: ["#26303C", "#8FA9C9"],
  },
  {
    id: "natural-wine-101",
    image: "/demo/natural-wine-101.jpg",
    title: "natural wine, zero snobbery",
    category: "talks-film",
    area: "peckham",
    venueName: "the glasshouse",
    hostName: "cork dork",
    dayOffset: 1,
    startTime: "19:30",
    price: 25,
    capacity: 40,
    going: 31,
    blurb: "six pours, no jargon. learn what you actually like and why.",
    tags: ["six pours", "beginners welcome"],
    palette: ["#2B2A36", "#A8A2C9"],
  },

  // ── this week ──
  {
    id: "amapiano-night",
    image: "/demo/amapiano-night.jpg",
    title: "piano nights: amapiano special",
    category: "nightlife",
    area: "brixton",
    venueName: "the loft",
    hostName: "piano nights",
    dayOffset: 3,
    startTime: "22:00",
    price: 12,
    capacity: 150,
    going: 122,
    blurb: "log drums until 3am. jerome okafor on the opening set.",
    talentNames: ["jerome okafor"],
    tags: ["late", "amapiano"],
    palette: ["#292433", "#8E7CA8"],
  },
  {
    id: "film-club-outdoor",
    image: "/demo/film-club-outdoor.jpg",
    title: "rooftop film club: in the mood for love",
    category: "talks-film",
    area: "peckham",
    venueName: "bussey rooftop",
    hostName: "reel south",
    dayOffset: 3,
    startTime: "21:00",
    price: 14,
    capacity: 90,
    going: 74,
    blurb: "wong kar-wai under the sky, headphones on, blankets out.",
    tags: ["headphones", "blankets provided"],
    palette: ["#2B2A36", "#A8A2C9"],
  },
  {
    id: "pasta-masterclass",
    image: "/demo/pasta-masterclass.jpg",
    title: "fresh pasta masterclass",
    category: "workshops",
    area: "bermondsey",
    venueName: "flour house",
    hostName: "nonna's table",
    dayOffset: 4,
    startTime: "18:00",
    price: 45,
    capacity: 16,
    going: 11,
    blurb: "hand-rolled tagliatelle from scratch, then you eat your homework.",
    tags: ["dinner included", "hands on"],
    palette: ["#3A2E1E", "#C2A968"],
  },
  {
    id: "vinyl-market",
    image: "/demo/vinyl-market.jpg",
    title: "crate diggers record fair",
    category: "markets",
    area: "deptford",
    venueName: "deptford market yard",
    hostName: "crate diggers",
    dayOffset: 4,
    startTime: "11:00",
    price: 0,
    capacity: 300,
    going: 96,
    blurb: "forty sellers, one yard, coffee that slaps. early entry for members.",
    tags: ["free entry", "early access drop"],
    palette: ["#28352B", "#7A9E6E"],
  },

  // ── the weekend ──
  {
    id: "sunday-league-fives",
    image: "/demo/sunday-league-fives.jpg",
    title: "sunday five-a-side pickup",
    category: "pickup-sports",
    area: "haggerston",
    venueName: "laburnum pitches",
    hostName: "casual fc",
    dayOffset: 5,
    startTime: "10:00",
    price: 6,
    capacity: 30,
    going: 24,
    blurb: "mixed-ability fives, bibs and balls sorted. winners stay on.",
    tags: ["mixed ability", "weekly"],
    palette: ["#26303C", "#8FA9C9"],
  },
  {
    id: "flea-and-food",
    image: "/demo/flea-and-food.jpg",
    title: "peckham flea & food yard",
    category: "markets",
    area: "peckham",
    venueName: "copeland park",
    hostName: "south side flea",
    dayOffset: 5,
    startTime: "10:00",
    price: 0,
    capacity: 500,
    going: 210,
    blurb: "vintage, ceramics, records and four food stalls. dogs welcome.",
    tags: ["free entry", "dogs welcome", "outdoors"],
    palette: ["#28352B", "#7A9E6E"],
  },
  {
    id: "sound-bath",
    image: "/demo/sound-bath.jpg",
    title: "saturday sound bath",
    category: "wellness",
    area: "london fields",
    venueName: "the round room",
    hostName: "still point",
    dayOffset: 5,
    startTime: "09:30",
    price: 18,
    capacity: 25,
    going: 21,
    blurb: "an hour under gongs and singing bowls. mats provided, phones off.",
    tags: ["mats provided", "morning"],
    palette: ["#243330", "#6E9CA0"],
  },
  {
    id: "block-party",
    image: "/demo/block-party.jpg",
    title: "rye lane block party",
    category: "nightlife",
    area: "peckham",
    venueName: "rye lane car park",
    hostName: "streets ahead",
    dayOffset: 6,
    startTime: "14:00",
    price: 8,
    capacity: 400,
    going: 287,
    blurb: "three sound systems, food from the yard, daytime into evening.",
    tags: ["outdoors", "family friendly until 7"],
    palette: ["#292433", "#8E7CA8"],
  },
  {
    id: "long-table-lunch",
    image: "/demo/long-table-lunch.jpg",
    title: "long table sunday lunch",
    category: "supper-clubs",
    area: "walthamstow",
    venueName: "the old baths",
    hostName: "gather round",
    dayOffset: 6,
    startTime: "13:00",
    price: 32,
    capacity: 60,
    going: 38,
    blurb: "one long table, four courses, strangers on purpose. seconds encouraged.",
    tags: ["four courses", "communal"],
    palette: ["#3A2E1E", "#C2A968"],
  },
  {
    id: "morning-rave",
    image: "/demo/morning-rave.jpg",
    title: "sober morning rave",
    category: "wellness",
    area: "shoreditch",
    venueName: "village underground",
    hostName: "daybreaker ldn",
    dayOffset: 6,
    startTime: "07:00",
    price: 15,
    capacity: 200,
    going: 134,
    blurb: "two hours of proper dancing before work exists. smoothies, not spirits.",
    tags: ["alcohol free", "morning"],
    palette: ["#243330", "#6E9CA0"],
  },

  // ── next week ──
  {
    id: "supper-club-vol-9",
    image: "/demo/supper-club-vol-9.jpg",
    title: "table for twelve — vol. 9",
    category: "supper-clubs",
    area: "peckham",
    venueName: "the glasshouse",
    hostName: "table for twelve",
    hostId: "maya",
    dayOffset: 9,
    startTime: "19:30",
    price: 30,
    capacity: 12,
    going: 7,
    blurb: "the flagship: twelve seats, five courses, one playlist built live by the table.",
    tags: ["twelve seats", "five courses"],
    palette: ["#3A2E1E", "#D4B461"],
  },
  {
    id: "poetry-open-mic",
    image: "/demo/poetry-open-mic.jpg",
    title: "unmuted: poetry open mic",
    category: "talks-film",
    area: "new cross",
    venueName: "the amersham arms",
    hostName: "unmuted",
    dayOffset: 8,
    startTime: "19:30",
    price: 5,
    capacity: 60,
    going: 26,
    blurb: "eight open slots, two features, one very kind room.",
    tags: ["open slots", "first timers cheered"],
    palette: ["#2B2A36", "#A8A2C9"],
  },
  {
    id: "banya-social",
    image: "/demo/banya-social.jpg",
    title: "banya & cold plunge social",
    category: "wellness",
    area: "canary wharf",
    venueName: "dock sauna",
    hostName: "hot cold club",
    dayOffset: 8,
    startTime: "18:00",
    price: 24,
    capacity: 20,
    going: 14,
    blurb: "steam, plunge, repeat — then tea and big talk on the deck.",
    tags: ["towels provided", "small group"],
    palette: ["#243330", "#6E9CA0"],
  },
  {
    id: "screen-print-crash",
    image: "/demo/screen-print-crash.jpg",
    title: "screen printing crash course",
    category: "workshops",
    area: "brixton",
    venueName: "print house",
    hostName: "pull & press",
    dayOffset: 10,
    startTime: "18:30",
    price: 28,
    capacity: 14,
    going: 6,
    blurb: "design, expose and pull your own two-colour print in one evening.",
    tags: ["take home", "materials included"],
    palette: ["#382B23", "#BC8E71"],
  },
  {
    id: "garage-revival",
    image: "/demo/garage-revival.jpg",
    title: "ukg revival: all vinyl",
    category: "nightlife",
    area: "hackney wick",
    venueName: "number 90",
    hostName: "steppers utd",
    dayOffset: 11,
    startTime: "21:00",
    price: 10,
    capacity: 180,
    going: 61,
    blurb: "two-step and 4x4 on wax until 2. dress code: comfortable shoes.",
    tags: ["vinyl only", "ukg"],
    palette: ["#292433", "#8E7CA8"],
  },
  {
    id: "makers-market",
    image: "/demo/makers-market.jpg",
    title: "small makers sunday market",
    category: "markets",
    area: "columbia road",
    venueName: "the courtyard",
    hostName: "made nearby",
    dayOffset: 12,
    startTime: "10:00",
    price: 0,
    capacity: 250,
    going: 44,
    blurb: "thirty local makers — ceramics, prints, small-batch everything.",
    tags: ["free entry", "local makers"],
    palette: ["#28352B", "#7A9E6E"],
  },
  {
    id: "climbing-social",
    image: "/demo/climbing-social.jpg",
    title: "beginners bouldering social",
    category: "pickup-sports",
    area: "bermondsey",
    venueName: "biscuit factory wall",
    hostName: "grip & grin",
    dayOffset: 12,
    startTime: "19:00",
    price: 14,
    capacity: 40,
    going: 18,
    blurb: "intro session, shoe hire included, pizza after. no upper-body strength required.",
    tags: ["beginners", "pizza after"],
    palette: ["#26303C", "#8FA9C9"],
  },

  // ── recently past — powers sofia's history, maya's track record, reviews ──
  {
    id: "table-vol-8",
    image: "/demo/table-vol-8.jpg",
    title: "table for twelve — vol. 8",
    category: "supper-clubs",
    area: "peckham",
    venueName: "the corner store",
    hostName: "table for twelve",
    hostId: "maya",
    dayOffset: -6,
    startTime: "19:30",
    price: 30,
    capacity: 12,
    going: 12,
    blurb: "twelve strangers, five courses, one very long argument about the best crisps.",
    tags: ["sold out"],
    palette: ["#3A2E1E", "#D4B461"],
  },
  {
    id: "table-vol-7",
    image: "/demo/table-vol-7.jpg",
    title: "table for twelve — vol. 7",
    category: "supper-clubs",
    area: "peckham",
    venueName: "the glasshouse",
    hostName: "table for twelve",
    hostId: "maya",
    dayOffset: -21,
    startTime: "19:30",
    price: 28,
    capacity: 12,
    going: 12,
    blurb: "the one with the plantain course everyone still talks about.",
    tags: ["sold out"],
    palette: ["#3A2E1E", "#D4B461"],
  },
  {
    id: "ceramics-past",
    image: "/demo/ceramics-past.jpg",
    title: "hackney ceramics evening",
    category: "workshops",
    area: "hackney",
    venueName: "mona's studio",
    hostName: "mona throws",
    dayOffset: -4,
    startTime: "18:30",
    price: 35,
    capacity: 12,
    going: 12,
    blurb: "hand-building session — pinch pots and small victories.",
    tags: ["hands on"],
    palette: ["#382B23", "#BC8E71"],
  },
  {
    id: "dub-past",
    image: "/demo/dub-past.jpg",
    title: "dub in the yard",
    category: "nightlife",
    area: "deptford",
    venueName: "arch 42",
    hostName: "heavyweight sound",
    dayOffset: -9,
    startTime: "20:00",
    price: 10,
    capacity: 120,
    going: 118,
    blurb: "one stack, one selector, no requests.",
    tags: ["sound system"],
    palette: ["#292433", "#8E7CA8"],
  },
];

export function eventById(id: string) {
  return SEED_EVENTS.find((e) => e.id === id);
}
