import type { BookingRequest, MessageThread, Review } from "./types";

/**
 * Seeded booking requests so venue/talent inboxes are never empty before the
 * judge creates anything. Requests generated by the create-event flow get
 * appended to these at runtime.
 */
export const SEED_REQUESTS: BookingRequest[] = [
  // the featured event's assembly — already accepted, shows the end state
  {
    id: "req-vs-venue",
    type: "venue",
    targetId: "glasshouse",
    eventId: "vinyl-and-supper",
    eventTitle: "jollof & vinyl",
    fromName: "tolu's table",
    dayOffset: 2,
    fee: 150000,
    note: "same setup as vol. 7 — long tables plus room to dance after nine.",
    status: "accepted",
  },
  {
    id: "req-vs-talent",
    type: "talent",
    targetId: "jerome-selects",
    eventId: "vinyl-and-supper",
    eventTitle: "jollof & vinyl",
    fromName: "tolu's table",
    dayOffset: 2,
    fee: 80000,
    note: "dinner set then dance set — bring the rare groove box.",
    status: "accepted",
  },
  // pending — live things for the venue/talent personas to act on
  {
    id: "req-glasshouse-wine",
    type: "venue",
    targetId: "glasshouse",
    eventId: "natural-wine-102",
    eventTitle: "wine & small chops, round two",
    fromName: "cork dork",
    dayOffset: 15,
    fee: 150000,
    note: "the first one sold out in a week. same layout, forty seats.",
    status: "pending",
  },
  {
    id: "req-glasshouse-print",
    type: "venue",
    targetId: "glasshouse",
    eventId: "print-fair-mini",
    eventTitle: "small print fair",
    fromName: "made nearby",
    dayOffset: 19,
    fee: 100000,
    note: "daytime — ten tables, gentle foot traffic, out by six.",
    status: "pending",
  },
  {
    id: "req-jerome-ukg",
    type: "talent",
    targetId: "jerome-selects",
    eventId: "garage-revival",
    eventTitle: "alté night: all vinyl",
    fromName: "steppers utd",
    dayOffset: 11,
    fee: 80000,
    note: "closing set, 12–2. wax only, obviously.",
    status: "pending",
  },
  {
    id: "req-jerome-lunch",
    type: "talent",
    targetId: "jerome-selects",
    eventId: "long-table-lunch",
    eventTitle: "long table sunday lunch",
    fromName: "gather round",
    dayOffset: 6,
    fee: 60000,
    note: "something warm and unhurried while people eat — sunday pace.",
    status: "pending",
  },
  // accepted — fills jerome's confirmed gigs and the venue calendar
  {
    id: "req-jerome-piano",
    type: "talent",
    targetId: "jerome-selects",
    eventId: "amapiano-night",
    eventTitle: "piano night: amapiano special",
    fromName: "piano nights",
    dayOffset: 3,
    fee: 90000,
    status: "accepted",
  },
  {
    id: "req-glasshouse-winetasting",
    type: "venue",
    targetId: "glasshouse",
    eventId: "natural-wine-101",
    eventTitle: "wine & small chops, zero snobbery",
    fromName: "cork dork",
    dayOffset: 1,
    fee: 150000,
    status: "accepted",
  },
];

export const SEED_THREADS: MessageThread[] = [
  {
    id: "thread-maya-priya",
    betweenPersonaIds: ["maya", "priya"],
    subject: "jollof & vinyl — final details",
    messages: [
      {
        fromPersonaId: "maya",
        text: "hey priya! confirming the date — can we get kitchen access from 4 for prep?",
        minutesAgo: 2880,
      },
      {
        fromPersonaId: "priya",
        text: "yes — i'll leave the side door open from 3:30. terrace is yours after nine too if the weather holds.",
        minutesAgo: 2760,
      },
      {
        fromPersonaId: "maya",
        text: "perfect. emeka's bringing two record boxes, is the deck setup still by the big monstera?",
        minutesAgo: 190,
      },
      {
        fromPersonaId: "priya",
        text: "moved it by the window — better light, same cables. see you on the night!",
        minutesAgo: 45,
      },
    ],
  },
  {
    id: "thread-sofia-maya",
    betweenPersonaIds: ["sofia", "maya"],
    subject: "jollof & vinyl — question",
    messages: [
      {
        fromPersonaId: "sofia",
        text: "hi! is jollof & vinyl veggie-friendly? bringing a friend who doesn't eat meat.",
        minutesAgo: 300,
      },
      {
        fromPersonaId: "maya",
        text: "completely — two of the three courses are plant-based and the third has a veggie version. just note it on your rsvp 🌿",
        minutesAgo: 240,
      },
    ],
  },
  {
    id: "thread-jerome-maya",
    betweenPersonaIds: ["jerome", "maya"],
    subject: "set times for jollof & vinyl",
    messages: [
      {
        fromPersonaId: "jerome",
        text: "thinking dinner set 7:30–9 stays low and warm, then i open it up. that work?",
        minutesAgo: 1500,
      },
      {
        fromPersonaId: "maya",
        text: "exactly right. dessert lands around 8:45 so build from there.",
        minutesAgo: 1440,
      },
    ],
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    eventTitle: "tolu's table — vol. 8",
    author: "dami",
    text: "came alone, left with three new group chats. the food was ridiculous.",
    rating: 5,
  },
  {
    eventTitle: "tolu's table — vol. 8",
    author: "hauwa",
    text: "tolu seats you like she's done a background check on your soul. 10/10.",
    rating: 5,
  },
  {
    eventTitle: "tolu's table — vol. 7",
    author: "olu",
    text: "still thinking about the plantain course. book it before it sells out.",
    rating: 5,
  },
  {
    eventTitle: "yaba ceramics evening",
    author: "amaka",
    text: "made a bowl that only slightly resembles a bowl. genuinely the most fun tuesday in ages.",
    rating: 4,
  },
  {
    eventTitle: "dub in the yard",
    author: "tunde",
    text: "one stack, no chat, chest-rattling. exactly as advertised.",
    rating: 5,
  },
];
